# Generated by Django 5.2.6 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(max_length=256)),
                ("location", models.CharField(max_length=256)),
            ],
        ),
    ]
