# Generated by Django 5.2.6 on 2025-09-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="users",
        ),
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="invited_user",
            field=models.ManyToManyField(
                blank=True, related_name="invited_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
